### ISSUE TITLE
Tether as coin

### ISSUE THREAD

**Issue by abdkaviani** [forgingblock/Multi-Coin-Crypto-Payment-Gateway#1]
Hi

In my Forgingblock dashboard, Tether address is connected.
and this lines:

`$data = array (`
`	"amount"=>1,`
`	"currency"=>"USD",`
`	"coin"=>"BTC",`
`	"order_id"=>'32165465',`
`	"notifyurl"=>$notifyURL,	`
`);`

BTC and ETH work as coin well, but can I use Tether as coin?

Thank you

**Comment by cryptofuture** [comment]
To get idea you might want to look at this: https://github.com/forgingblock/ipn-code-samples/tree/master/NodeJS#building-it-all-out
But basically to achieve in own payment form you need:
1. Connect required wallet addresses
2. Create invoice
3. Make a request to `https://api.forgingblock.io/i/invoiceId/eth-token/USDT/status?invoiceId=invoiceId&paymentMethodId=USDT&_=1`
4. Load data from response of that request in the payment form, either handle using IPN or do requests to the status url continuously before invoice lifetime is over

Example in this repo is simple, but its far away from perfect. **And you probably don't need to spend time for that in most scenarios, as you could just use official payment form**

Also I doubt ETH would work in that example, and its probaly working only because its under same root path like BTC.

there a few more paths, while cryptocurrencies (not tokens are under root path)
```
/eth-token/
/tron-token/
/eos-token/
/bsc-token/
```

**Comment by JaqenSyrio** [comment]
@senthil1975 , can you please help?

**Comment by senthil1975** [comment]
use like this 
"coin"=>"eth-token/USDT"

**Comment by abdkaviani** [comment]
Thanks
It works :)
